### PR TITLE
add basic pub-sub support to event managers

### PR DESCRIPTION
**Pull request by kevbob1**
i like the module. I needed a way to distribute websocket messages/broadcasts across processes.  I plan to use redis pubsub for that.   if there is interest, i could include the redis PubSub in this gem or keep it separate in my app (or another gem).

Cheers,  Kevin

### CODE REVIEW

**Comment by dariocravero** [comment]
Hey @kevbob1, thanks for your interest! I'm not actively maintaining this project anymore. I'm happy to make you an owner if you want to take it over! Cheers, Darío

**Comment by kevbob1** [comment]
Hi Dario,  I would be happy to take over.   Let me know what i need to do.
(if anything)

---
Kevin

**Comment by dariocravero** [comment]
I just gave you access to the repo. I'll need to look at how to give you access to the process to publish the gem. It's been a long while since I've done that so I hope I can find where that is 🙈.

**Comment by dariocravero** [comment]
Right, I think I figured it out @kevbob1. It looks like I'd need to give you access to publish at rubygems.org. Do you have an account there? If you don't, could you create it and share with me your username and email? Thanks!

**Comment by kevbob1** [comment]
emailed info.  cheers!

**Comment by dariocravero** [comment]
Done! :)

**Pull request merged**
